# Generated by Django 5.2 on 2025-07-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_aboutusimages_homepagesliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirybooking',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
