# Generated by Django 5.2 on 2025-08-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_services_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesliderimage',
            name='mobileImage',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/'),
        ),
    ]
