# Generated by Django 5.2 on 2025-08-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_serviceenquiry_vehicleduration_delete_serviceclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookadventure',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_images/'),
        ),
        migrations.AlterField(
            model_name='bookadventure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_images/'),
        ),
    ]
